repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_fmt
        args:
          - --args=-check
          - --args=-diff
          - --args=-recursive
      - id: terraform_validate
      - id: terraform_tflint
        args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=--call-module-type="all"
        - --args=--recursive
      - id: terraform_checkov
        args:
        - --args=--quiet
      - id: terraform_docs
        args:
        - --args=--config=.terraform-docs.yml
        - --hook-config=--add-to-exiting-file=false
        - --hook-config=--create-file-if-not-exist=true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
